services:
  api:
    container_name: ring-api
    build: ./ring
    command: "uvicorn ring.fast:app --log-level debug --host 0.0.0.0 --port ${API_PORT} --reload"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./ring:/src/ring
    env_file:
      - ./.env
    environment:
      - AWS_ACCESS_KEY_ID='DUMMYIDEXAMPLE'
      - AWS_SECRET_ACCESS_KEY='DUMMYEXAMPLEKEY'
      - REGION='us-east-1'
      - PYTHONPATH=.
    depends_on:
      - db
    links:
      - db
  redis:
    image: redis:alpine
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port ${DB_PORT}"
    image: "amazon/dynamodb-local:latest"
    container_name: ring-db 
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

volumes:
  dynamodb: